"""Adding TicTacToeGame

Revision ID: 247a4b6d636a
Revises: 88142eb1b4a4
Create Date: 2024-04-27 15:11:45.563656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247a4b6d636a'
down_revision = '88142eb1b4a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_token', sa.Integer(), nullable=False),
    sa.Column('is_game_started', sa.Boolean(), nullable=False),
    sa.Column('is_game_ended', sa.Boolean(), nullable=False),
    sa.Column('user_host_id', sa.Integer(), nullable=False),
    sa.Column('user_guest_id', sa.Integer(), nullable=True),
    sa.Column('user_turn', sa.Boolean(), nullable=False),
    sa.Column('game_turn', sa.Integer(), nullable=False),
    sa.Column('game_data', sa.String(length=255), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_guest_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_host_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['winner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
