"""Rework model

Revision ID: 41222a26273a
Revises: 247a4b6d636a
Create Date: 2024-04-27 19:43:43.291067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41222a26273a'
down_revision = '247a4b6d636a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('is_game_started',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('is_game_ended',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('user_turn',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('game_turn',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('winner',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('winner',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('game_turn',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('user_turn',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
        batch_op.alter_column('is_game_ended',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('is_game_started',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###
