"""CHanges in tic tac toe

Revision ID: f59e01d5032a
Revises: c47d9b5cd63c
Create Date: 2024-05-03 20:36:58.713528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f59e01d5032a'
down_revision = 'c47d9b5cd63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('game_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_data', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
